package com.example.openinapp.data.api.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

// TODO [COMPLETED] -> Generated by "Kotlin data class file from JSON" Extension.

@Serializable
data class Data(
    @SerialName("favourite_links")
    val favouriteLinks: List<RecentLink>,

    // I updated this one, because extension generator was incorrect.
    @SerialName("overall_url_chart")
    val overallUrlChart: Map<String, Int>,

    @SerialName("recent_links")
    val recentLinks: List<RecentLink>,
    @SerialName("top_links")
    val topLinks: List<TopLink>
)